dist: xenial
language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - flake8
  - bandit -r infoblox
  - cd tests
  - pytest

after_script:
  - codecov