dist: xenial
language: python
env:
  global:
    secure: boSfme7jdyZCnuFuwxeNAEih3s4ilz1uyWeY0uXBCPYIVMO5ofj8hu8iU4Y4evP8ckgxtS481+F9TMjgkXFZVd5ZtQyCAmvPlSOOx3vOzR91aIlf1d9uYaWRzmrSsucN+SAfz+N5+FJwJt46CWxeD59EFI+YEPBYifDlNSxzWWojlmD3Ii8NZkfKdrVLxYOgL6CDXv2o2+eh6SFxj4aEenbqGVbQkjvGqDJTy4uPW8Pi5XhhBNJ1uM8SLcsD2EXwb28d73mXHJrNKf5nqTqe8wmr8oUiJzdwRBHTaUJthFC7DHV9jKBZGZMu0vDOWLXr1OsRocZuARRv2UBp7uns8jRfzO7mpBSxgJ0FJuz6NSaHlIF+pqR+iA7OQGAua6d9+WzkfvD/MVjYH+rOg6L6oLZChn2gZndeHmg7Yrt7a/2zx2wbsrTYL1WbZb4KNN+mT+ys+QkF0dGoulv2iy7+pRNRIf5PhUU3izs5ECC3OK86gGv1uxVZgiCf0lH/O8vwul8DpgAGAY2RPqCBiVtafX1DzcdjyFbrTDx2PEfghW9UMTG7RXrBncJWhLhescT9BlFq4W7i/tJnHIiND/9icQOQbW6aRkkNtJMsnI94kyd54IAjO9AbFn3Y8i9EPtn5kbm3nazbKuIH2x486eR+mVfv04/L6YgS5sCqEMEiY8I=

matrix:
  include:
    - python: '3.6'
      env: NOXSESSION=tests-3.6
    - python: '3.7'
      env: NOXSESSION=tests-3.7
    - python: '3.8'
      env: NOXSESSION=tests-3.8
    - python: '3.8'
      env: NOXSESSION=lint
    - python: '3.8'
      env: NOXSESSION=docs

install: pip install -U pip setuptools nox

script: nox -s $NOXSESSION

deploy:
  provider: script
  script: nox -s deploy
  on:
    tags: true
    branch: master
    repo: lewoudar/configuror
    condition: "$NOXSESSION = tests-3.8"
