init:
  - SET PATH=%PYTHON%;%PATH%

environment:
  matrix:
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38-x64


install:
  - python -m pip install nox

build: off

test_script:
  - nox -s lint tests