site_name: Configuror
site_description: configuror package documentation
site_author: Kevin Tewouda
site_url: https://configuror.readthedocs.io

repo_url: https://github.com/lewoudar/configuror/
edit_uri: tree/master/docs

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API: api.md

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      css_class: highlight
